<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'help' => null,
    'sourcePath' => Yii::getAlias('@root_path'), //alias personalizado para acceder a raiz del proyecto(ver params-local)
    'languages' => ['en'],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => false,
    'removeUnused' => true,
    'markUnused' => false,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
        '/BaseYii.php',
        '/vendor',
        '/console',
        '/environments',
        '/vagrant'
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'db',
    'db' => 'db',
    'sourceMessageTable' => '{{%source_message}}',
    'messageTable' => '{{%message}}',
    'catalog' => 'messages',
    'ignoreCategories' => ['yii','app','rbac-admin'],
    'phpFileHeader' => '',
    'phpDocBlock' => null,
];
